language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
  - "3.5"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get install python3-pip python-dev python3-dev
  - git clone https://gitlab.com/ideasman42/blender-mathutils.git
  - cd blender-mathutils
  - python setup.py build
  - sudo python setup.py install

install:
  - pip install pytest
  - pip install --only-binary=numpy,scipy numpy scipy

before_script:
  - python -V

script:
  - python setup.py install

notifications:
  email: false
